import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/ui/ThemeProvider'

export const metadata: Metadata = {
  title: 'FTM 2.0',
  description: 'Generated by GMARTE.COM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className='bg-[#F5F6F8]'> */}
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >        
        {children}        
        <Modal />
        </ThemeProvider>
      </body>
    </html>
  )
}
